Repository HorizonRobotics/alf, pull requests merged in 2022-04, with the labels that each got.

#1278 Predicting policy becomes optional in MuZero
  alf/algorithms/mcts_models.py
  alf/algorithms/muzero_representation_learner.py
Labels: features

#1273 improve vae
  alf/algorithms/merlin_algorithm.py
  alf/algorithms/vae.py
  alf/algorithms/vae_test.py
Labels: enhancement

#1270 Add visualization of the MCTSTrees
  alf/algorithms/mcts_algorithm.py
Labels: features

#1282 ALF will save a visualization of the algorithm module structure
  alf/trainers/policy_trainer.py
Labels: features

#1284 Improve SequentialDataTransformer's order validation for UntransformedTimeStep
  alf/algorithms/data_transformer.py
  docs/notes/knowledge_base.rst
Labels: enhancement

#1288 Fix outlier cases in algorithm visualization
  alf/trainers/policy_trainer.py
Labels: enhancement

#1289 Fix a few bugs and warnings in muzero experiments
  alf/algorithms/algorithm.py
  alf/algorithms/mcts_algorithm.py
  alf/algorithms/mcts_models.py
  alf/algorithms/muzero_algorithm_test.py
  alf/algorithms/muzero_representation_learner.py
  alf/environments/suite_metadrive.py
Labels: bug

#1290 Algorithm can optionally choose to expose already-handled parameters to its parent
  alf/algorithms/algorithm.py
Labels: features
